name: 部署到腾讯云函数

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "安装依赖和serverless工具"
        run: |
          npm install
          sudo npm install serverless -g

      - name: "将Secrets里面配置的变量添加到severless.yml里面作为环境变量"
        run: |
          if [ $QQ_READ_COOKIE ]; then sed -i "/variables/a\      QQ_READ_COOKIE: $QQ_READ_COOKIE" serverless.yml; fi;
          if [ $QQ_READ_COOKIE2 ]; then sed -i "/variables/a\      QQ_READ_COOKIE2: $QQ_READ_COOKIE2" serverless.yml; fi;
          cat serverless.yml
          env
        env: #因为直接读取secrets里面的值很多字符不会自动转译，导致写入serverless.yml异常，所以设置到环境变量，在读取环境变量转译过的值
          QQ_READ_COOKIE: ${{ secrets.QQ_READ_COOKIE}}
          QQ_READ_COOKIE2: ${{ secrets.QQ_READ_COOKIE2}}

      - name: "部署到腾讯云函数"
        run: serverless deploy
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
