# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: flw返利网

on:
  workflow_dispatch:
  schedule:
     - cron: '35 0,3,8,11 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build:
    env:
      FL_flwURL: ${{ secrets.FL_flwURL }}
      FL_flwHEADER: ${{ secrets.FL_flwHEADER }}
      FL_flwspBODY: ${{ secrets.FL_flwspBODY }}
      FL_flwqwBODY: ${{ secrets.FL_flwqwBODY }}
      FL_flwydBODY: ${{ secrets.FL_flwydBODY }}
      FL_CASH: ${{ secrets.FL_CASH }}
      FL_DHCASH: ${{ secrets.FL_DHCASH }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}


    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update

      - name: '运行 【flw返利网】'
        if: env.FL_flwURL
        run: |
          cd ~/Scripts
          node Task/flw.js
        env:
          FL_flwURL: ${{ secrets.FL_flwURL }}
          FL_flwHEADER: ${{ secrets.FL_flwHEADER }}
          FL_flwspBODY: ${{ secrets.FL_flwspBODY }}
          FL_flwqwBODY: ${{ secrets.FL_flwqwBODY }}
          FL_flwydBODY: ${{ secrets.FL_flwydBODY }}
          FL_CASH: ${{ secrets.FL_CASH }}
          FL_DHCASH: ${{ secrets.FL_DHCASH }}
