name: 番茄看看

on:
    workflow_dispatch:
    schedule:
      - cron: "5 0,1,2,3 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: fqkk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: adw2s/Action              

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【1】'
        run: |
          node Task/fqkk.js
        env:
          fqkkurl: ${{ secrets.fqkkurl }}
          fqkkhd: ${{ secrets.fqkkhd }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}