name: qqread

on:
  #schedule:
    #- cron: '*/20 * * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: qqread
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QQ_READ_COOKIE: ${{ secrets.QQ_READ_COOKIE }}
      QQ_READ_COOKIE2: ${{ secrets.QQ_READ_COOKIE2 }}
      DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
      DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./qqread/requirements.txt 
        
      - name: 'qqread一' 
        run: python3 ./qqread/qqread.py
        env:
            QQ_READ_COOKIE: ${{ secrets.QQ_READ_COOKIE }}       
      - name: 'qqread二'
        run: python3 ./qqread/qqread.py
        env:
            QQ_READ_COOKIE: ${{ secrets.QQ_READ_COOKIE2 }}