name: 企鹅读书py

on:
  workflow_dispatch:
  #schedule:
    #- cron: '*/11 * * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: qqreadspy
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Water008/qqread
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行【企鹅读书】' 
        run: python3 qqread.py 
        env:
            QQREADHEADERS: ${{ secrets.QQREADHEADERS }}
            QQREADBODYS: ${{ secrets.QQREADBODYS }}
            QQREADTIMEURL: ${{ secrets.QQREADTIMEURL }}
            NOTIFYTYPE: ${{ secrets.NOTIFYTYPE }}
            NOTIFYCFG: ${{ secrets.NOTIFYCFG }}
            SCKEY: ${{ secrets.SCKEY }}
            BARK: ${{ secrets.BARK }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}