# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 走路赚钱

on:
    workflow_dispatch:
    schedule:
      - cron: "5 */1 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: allenqq1209/allen              

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【zlzq】'
        run: |
          node task/runstep.js
        env:
          RUNSTEP_TOKEN: ${{ secrets.RUNSTEP_TOKEN }}
        RUNSTEP_KEY: ${{ secrets.RUNSTEP_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}