name: 喜马拉雅极速版

on:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: xmly
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Zero-S1/xmly_speed
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'run 喜马拉雅极速版' 
        run: python3 xmly_speed.py
      - name: '休息3分钟'
        uses: jakejarvis/wait-action@master
        with:
          time: '3m'
      - name: 'run 喜马拉雅极速版2' 
        run: python3 xmly_speed.py 
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须
            # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }} #非私密信息，去掉
            BARK: ${{ secrets.BARK }}     # bark服务
            SCKEY: ${{ secrets.SCKEY }}   # server酱服务
            TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
            TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id
    
