# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 笑live

on:
    workflow_dispatch:
    #schedule:
      #- cron: "0 0-15/1 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: smile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【1】'
        run: |
          node Node/XPZB.js
      - name: '休息2分钟'
        uses: jakejarvis/wait-action@master
        with:
          time: '2m'
      - name: '运行 【2】'
        run: |
          node Node/XPZB.js
      - name: '休息2分钟'
        uses: jakejarvis/wait-action@master
        with:
          time: '2m'
      - name: '运行 【3】'
        run: |
          node Node/XPZB.js
      - name: '休息2分钟'
        uses: jakejarvis/wait-action@master
        with:
          time: '2m'
      - name: '运行 【4】'
        run: |
          node Node/XPZB.js
      - name: '休息2分钟'
        uses: jakejarvis/wait-action@master
        with:
          time: '2m'
      - name: '运行 【5】'
        run: |
          node Node/XPZB.js
        env:
          XP_CASH: ${{ secrets.XP_CASH }}
          XP_live: ${{ secrets.XP_live }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}